apiVersion: apps/v1
kind: Deployment
metadata:
  name: webserver-deploy-app-user
  labels:
    env: dev
spec:
  replicas: 2
  selector:
    matchLabels:
      tier: web-server
  template:
    metadata:
      name: diegoapp
      labels:
        tier: web-server
    spec:
      containers:
        - name: diegoapp
          image: logfile1995/diegokuber:calbekuber
          ports:
            - name: diegoapp
              containerPort: 80