apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: jenkins-res
  labels:
    env: test
  namespace: test
spec:
  replicas: 2
  selector:
    matchLabels:
      tier: jenkins
  template:
    metadata:
      name: jenkins
      labels:
        tier: jenkins
    spec:
      containers:
        - name: jenkins
          image: jenkins/jenkins
          ports:
            - name: jenkins
              containerPort: 80