apiVersion: v1
kind: Service
metadata:
  name: mysql-svc
  labels:
    tier: web-server
spec:
  type: ClusterIP
  selector:
    tier: web-server
  ports:
    - protocol: TCP
      name: mysqlapp
      targetPort: 3306
      port: 3306